export const CARD_ADD_ITEM = 'CARD_ADD_ITEM'
export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'

export const CARD_SAVE_PAYMENT_METHOD = 'CARD_SAVE_PAYMENT_METHOD'

export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'
