# Generated by Django 4.2.4 on 2023-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proshop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='./static/images/placeholder.png', null=True, upload_to=''),
        ),
    ]
